# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy Web Application

on:
  push:
    branches: [ "master" ]

env:
  AZURE_WEBAPP_NAME: USCSAdoctorNotesPoc
  AZURE_WEBAPP_PATH: './web-app/CognitiveSearch.UI/'
  DOTNET_VERSION: '3.1.302'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: 
        dotnet restore ./web-app/
        dotnet restore ./web-app/CognitiveSearch.UI/CognitiveSearch.UI.csproj
      
    - name: Build
      run: 
         dotnet build --configuration release
         dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PATH }}/publish'
      
    - name: Deploy to App Service
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: '${{ env.AZURE_WEBAPP_PATH }}/publish'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} 
    
